-- ma puppet --

-- materials
red = gr.material({1.0, 0.0, 0.0}, {0.1, 0.1, 0.1}, 10)
green = gr.material({0.0, 1.0, 0.0}, {0.1, 0.1, 0.1}, 10)
blue = gr.material({0.0, 0.0, 1.0}, {0.1, 0.1, 0.1}, 10)
white = gr.material({1.0, 1.0, 1.0}, {0.1, 0.1, 0.1}, 10)

-- puppet model
puppet = gr.node("puppet")

torso_node = gr.node('torso_node')
torso = gr.sphere('torso')
torso:scale(0.9, 1.5, 0.9)
torso:set_material(green)
puppet:add_child(torso_node)
puppet:add_child(torso)

shoulders_node = gr.node('shoulders_node')
shoulders = gr.sphere('shoulders')
shoulders_node:translate(0,1.3,0)
shoulders:translate(0,1.3,0)
shoulders:scale(1.5,0.4,1.0)
shoulders:set_material(blue)
torso_node:add_child(shoulders_node)
torso_node:add_child(shoulders)

neck_joint = gr.joint('neck_joint',{-10,0,10},{0,0,0})
neck_node = gr.node('neck_node')
neck = gr.sphere('neck')
neck_joint:translate(0,0.4,0)
neck_node:translate(0,0.1,0)
neck:translate(0,0.1,0)
neck:scale(1,1.5,1) -- proportions
neck:scale(.2,.2,.2) -- relative size
neck:set_material(green)
shoulders_node:add_child(neck_joint)
neck_joint:add_child(neck_node)
neck_joint:add_child(neck)

head_joint = gr.joint('head_joint',{-30,0,30},{-80,0,80})
head_node = gr.node('head_node')
head = gr.sphere('head')
head_joint:translate(0,0.1,0)
head_node:translate(0,0.6,0)
head:translate(0,0.6,0)
head:scale(.6,.6,.6)
head:set_material(red)
neck_node:add_child(head_joint)
head_joint:add_child(head_node)
head_joint:add_child(head)

noes_node = gr.node('noes_node')
noes = gr.sphere('noes')
noes_node:translate(0,0,0.62)
noes:translate(0,0,0.62)
noes:scale(.1,.1,.1)
noes:set_material(blue)
head_node:add_child(noes_node)
head_node:add_child(noes)

-- shoulders scale (1.5,0.4,1.0)
luparm_joint = gr.joint('luparm_joint',{-170,0,50},{0,0,0})
luparm_node = gr.node('luparm_node')
luparm = gr.sphere('luparm')
luparm_joint:translate(1.45,0,0)
luparm_node:translate(0,-0.75,0)
luparm:translate(0,-0.75,0)
luparm:scale(1,2.5,1) -- proportions
luparm:scale(.3,.3,.3) -- proportions
luparm:set_material(red)
shoulders_node:add_child(luparm_joint)
luparm_joint:add_child(luparm_node)
luparm_joint:add_child(luparm)

ruparm_joint = gr.joint('ruparm_joint',{-170,0,50},{0,0,0})
ruparm_node = gr.node('ruparm_node')
ruparm = gr.sphere('ruparm')
ruparm_joint:translate(-1.45,0,0)
ruparm_node:translate(0,-0.75,0)
ruparm:translate(0,-0.75,0)
ruparm:scale(1,2.5,1) -- proportions
ruparm:scale(.3,.3,.3) -- relative size
ruparm:set_material(red)
shoulders_node:add_child(ruparm_joint)
ruparm_joint:add_child(ruparm_node)
ruparm_joint:add_child(ruparm)

lforearm_joint = gr.joint('lforearm_joint',{-150,0,0},{0,0,0})
lforearm_node = gr.node('lforearm_node')
lforearm = gr.sphere('lforearm')
lforearm_joint:translate(0,-0.75,0)
lforearm_node:translate(0,-0.70,0)
lforearm:translate(0,-0.70,0)
lforearm:scale(.9,2.5,.9) -- proportions
lforearm:scale(.3,.3,.3) -- relative size
lforearm:set_material(blue)
luparm_node:add_child(lforearm_joint)
lforearm_joint:add_child(lforearm_node)
lforearm_joint:add_child(lforearm)

rforearm_joint = gr.joint('rforearm_joint',{-150,0,0},{0,0,0})
rforearm_node = gr.node('rforearm_node')
rforearm = gr.sphere('rforearm')
rforearm_joint:translate(0,-0.75,0)
rforearm_node:translate(0,-0.70,0)
rforearm:translate(0,-0.70,0)
rforearm:scale(.9,2.5,.9) -- proportions
rforearm:scale(.3,.3,.3) -- relative size
rforearm:set_material(blue)
ruparm_node:add_child(rforearm_joint)
rforearm_joint:add_child(rforearm_node)
rforearm_joint:add_child(rforearm)

lhand_joint = gr.joint('lhand_joint',{-30,0,30},{0,0,0})
lhand_node = gr.node('lhand_node')
lhand = gr.sphere('lhand')
lhand_joint:translate(0,-0.75,0)
lhand_node:translate(0,-0.15,0)
lhand:translate(0,-0.25,0)
lhand:scale(1,1,1) -- proportions
lhand:scale(.3,.3,.3) -- relative size
lhand:set_material(green)
lforearm_node:add_child(lhand_joint)
lhand_joint:add_child(lhand_node)
lhand_joint:add_child(lhand)

rhand_joint = gr.joint('rhand_joint',{-30,0,30},{0,0,0})
rhand_node = gr.node('rhand_node')
rhand = gr.sphere('rhand')
rhand_joint:translate(0,-0.75,0)
rhand_node:translate(0,-0.15,0)
rhand:translate(0,-0.25,0)
rhand:scale(1,1,1) -- proportions
rhand:scale(.3,.3,.3) -- relative size
rhand:set_material(green)
rforearm_node:add_child(rhand_joint)
rhand_joint:add_child(rhand_node)
rhand_joint:add_child(rhand)

hips_node = gr.node('hips_node')
hips = gr.sphere('hips')
hips_node:translate(0,-1.3,0)
hips:translate(0,-1.3,0)
hips:scale(1.0,0.4,1.0)
hips:set_material(red)
torso_node:add_child(hips_node)
torso_node:add_child(hips)

lthigh_joint = gr.joint('lthigh_joint',{-90.0,0,10.0},{0,0,0})
lthigh_node = gr.node('lthigh_node')
lthigh = gr.sphere('lthigh')
lthigh_joint:translate(0.7,-0.1,0)
lthigh_node:translate(0,-1,0)
lthigh:translate(0,-1,0)
lthigh:scale(0.3,1,0.3)
lthigh:set_material(blue)
hips_node:add_child(lthigh_joint)
lthigh_joint:add_child(lthigh_node)
lthigh_joint:add_child(lthigh)

rthigh_joint = gr.joint('rthigh_joint',{-90.0,0,10.0},{0,0,0})
rthigh_node = gr.node('rthigh_node')
rthigh = gr.sphere('rthigh')
rthigh_joint:translate(-0.7,-0.1,0)
rthigh_node:translate(0,-1,0)
rthigh:translate(0,-1,0)
rthigh:scale(0.3,1,0.3)
rthigh:set_material(blue)
hips_node:add_child(rthigh_joint)
rthigh_joint:add_child(rthigh_node)
rthigh_joint:add_child(rthigh)

lcalf_joint = gr.joint('lcalf_joint',{0,0,140},{0,0,0})
lcalf_node = gr.node('lcalf_node')
lcalf = gr.sphere('lcalf')
lcalf_joint:translate(0,-1,0)
lcalf_node:translate(0,-0.7,0)
lcalf:translate(0,-0.7,0)
lcalf:scale(0.3,0.8,0.3)
lcalf:set_material(green)
lthigh_node:add_child(lcalf_joint)
lcalf_joint:add_child(lcalf_node)
lcalf_joint:add_child(lcalf)

rcalf_joint = gr.joint('rcalf_joint',{0,0,140},{0,0,0})
rcalf_node = gr.node('rcalf_node')
rcalf = gr.sphere('rcalf')
rcalf_joint:translate(0,-1,0)
rcalf_node:translate(0,-0.7,0)
rcalf:translate(0,-0.7,0)
rcalf:scale(0.3,0.8,0.3)
rcalf:set_material(green)
rthigh_node:add_child(rcalf_joint)
rcalf_joint:add_child(rcalf_node)
rcalf_joint:add_child(rcalf)

lfoot_joint = gr.joint('lfoot_joint',{-30,0,60},{0,0,0})
lfoot_node = gr.node('lfoot_node')
lfoot = gr.sphere('lfoot')
lfoot_joint:translate(0,-0.8,0)
lfoot_node:translate(0,0,0.3)
lfoot:translate(0,0,0.3)
lfoot:scale(1.5,1,2)
lfoot:scale(.2,.2,.2)
lfoot:set_material(red)
lcalf_node:add_child(lfoot_joint)
lfoot_joint:add_child(lfoot_node)
lfoot_joint:add_child(lfoot)

rfoot_joint = gr.joint('rfoot_joint',{-30,0,60},{0,0,0})
rfoot_node = gr.node('rfoot_node')
rfoot = gr.sphere('rfoot')
rfoot_joint:translate(0,-0.8,0)
rfoot_node:translate(0,0,0.3)
rfoot:translate(0,0,0.3)
rfoot:scale(1.5,1,2)
rfoot:scale(.2,.2,.2)
rfoot:set_material(red)
rcalf_node:add_child(rfoot_joint)
rfoot_joint:add_child(rfoot_node)
rfoot_joint:add_child(rfoot)

puppet:translate(0,0,-15);

return puppet;
